// Genere CLQ App Factory v2026.06.25-tts-polly-generative
const locations=[
    { name: "Palacio Consistorial de Carthagène", lat: 37.59934, lng: -0.98594, audio: "audio/Palacio_Consistorial_de_Carthagene.mp3", image: "images/points interets/palacio-consistorial-de-carthagene.jpg", fallbackImage: "images/points interets/Palacio_Consistorial_de_Carthagene.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Palacio_Municipal_de_Cartagena.jpg" },
    { name: "Théâtre Romain", lat: 37.59950277231625, lng: -0.9841131454508256, audio: "audio/Theatre_Romain.mp3", image: "images/points interets/theatre-romain.jpg", fallbackImage: "images/points interets/Theatre_Romain.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Teatro_Romano_de_Cartagena_2.jpg" },
    { name: "Castillo de la Concepción", lat: 37.60019577223688, lng: -0.9821462031216204, audio: "audio/Castillo_de_la_Concepcion.mp3", image: "images/points interets/castillo-de-la-concepcion.jpg", fallbackImage: "images/points interets/Castillo_de_la_Concepcion.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/3/39/Cartagena_-_Castillo_de_la_Concepci%C3%B3n_01_2017-05-27.jpg" },
    { name: "Quartier du Forum Romain", lat: 37.60208071851756, lng: -0.9856296715995001, audio: "audio/Quartier_du_Forum_Romain.mp3", image: "images/points interets/quartier-du-forum-romain.jpg", fallbackImage: "images/points interets/Quartier_du_Forum_Romain.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Foro_Romano_de_Cartagena_1.jpg" },
    { name: "La Casa de la Fortuna", lat: 37.60224097209364, lng: -0.9820721319569341, audio: "audio/La_Casa_de_la_Fortuna.mp3", image: "images/points interets/la-casa-de-la-fortuna.jpg", fallbackImage: "images/points interets/La_Casa_de_la_Fortuna.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Casa_de_la_Fortuna,_Cartagena_(6089786822).jpg" },
    { name: "Muraille Punique", lat: 37.604131098035005, lng: -0.9786499147791006, audio: "audio/Muraille_Punique.mp3", image: "images/points interets/muraille-punique.jpg", fallbackImage: "images/points interets/Muraille_Punique.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/3/31/Cartagena_muralla_punica.jpg" },
    { name: "Museo Nacional de Arqueología Subacuática (ARQUA)", lat: 37.597665571913886, lng: -0.9802508454509145, audio: "audio/Museo_Nacional_de_Arqueologia_Subacuatica_ARQUA.mp3", image: "images/points interets/museo-nacional-de-arqueologia-subacuatica-arqua.jpg", fallbackImage: "images/points interets/Museo_Nacional_de_Arqueologia_Subacuatica_ARQUA.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/f/fe/080113-039-CT_ARQUA-MUSEO_ARQUEOLOGIA-800.jpg" },
    { name: "Le Port de Carthagène", lat: 37.59735447256233, lng: -0.9836170454508865, audio: "audio/Le_Port_de_Carthagene.mp3", image: "images/points interets/le-port-de-carthagene.jpg", fallbackImage: "images/points interets/Le_Port_de_Carthagene.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Puerto_de_Cartagena.jpg" },
    { name: "Calle Mayor et Gran Hotel", lat: 37.599804, lng: -0.98562, audio: "audio/Calle_Mayor_et_Gran_Hotel.mp3", image: "images/points interets/calle-mayor-et-gran-hotel.jpg", fallbackImage: "images/points interets/Calle_Mayor_et_Gran_Hotel.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Calle_Mayor_in_Cartagena,_Spain.jpg" },
    { name: "Gran Hotel", lat: 37.59907, lng: -0.98537, audio: "audio/Gran_Hotel.mp3", image: "images/points interets/gran-hotel.jpg", fallbackImage: "images/points interets/Gran_Hotel.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Gran_Hotel_Cartagena.jpg" },
    { name: "Plaza de San Francisco et Casa Maestre", lat: 37.60075, lng: -0.98435, audio: "audio/Plaza_de_San_Francisco_et_Casa_Maestre.mp3", image: "images/points interets/plaza-de-san-francisco-et-casa-maestre.jpg", fallbackImage: "images/points interets/Plaza_de_San_Francisco_et_Casa_Maestre.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Gran_Hotel_Cartagena.jpg" },
    { name: "Museo Histórico Militar de Cartagena", lat: 37.60470587115126, lng: -0.9854373607922013, audio: "audio/Museo_Historico_Militar_de_Cartagena.mp3", image: "images/points interets/museo-historico-militar-de-cartagena.jpg", fallbackImage: "images/points interets/Museo_Historico_Militar_de_Cartagena.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Museo_de_Artiller%C3%ADa_Patio_de_Armas_Derecha.jpg" },
    { name: "Sous-marin Isaac Peral", lat: 37.598283, lng: -0.979711, audio: "audio/Sous_marin_Isaac_Peral.mp3", image: "images/points interets/sous-marin-isaac-peral.jpg", fallbackImage: "images/points interets/Sous_marin_Isaac_Peral.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/1/10/Peral_Submarine_Cartagena,ES_2011.jpg" },
    { name: "Ascensor Panorámico", lat: 37.600167, lng: -0.981235, audio: "audio/Ascensor_Panoramico.mp3", image: "images/points interets/ascensor-panoramico.jpg", fallbackImage: "images/points interets/Ascensor_Panoramico.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Ascensor_panor%C3%A1mico_in_Cartagena,_Murcia,_Spain,_2022_January.jpg" },
    { name: "Museo-Refugio de la Guerre Civile", lat: 37.60008, lng: -0.98086, audio: "audio/Museo_Refugio_de_la_Guerre_Civile.mp3", image: "images/points interets/museo-refugio-de-la-guerre-civile.jpg", fallbackImage: "images/points interets/Museo_Refugio_de_la_Guerre_Civile.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/3/35/Museo-Refugio_de_la_Guerra_Civil_(20210313_190419).jpg" },
    { name: "Anfiteatro Romano", lat: 37.6007093, lng: -0.9799511, audio: "audio/Anfiteatro_Romano.mp3", image: "images/points interets/anfiteatro-romano.jpg", fallbackImage: "images/points interets/Anfiteatro_Romano.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Anfiteatro_cartagena.jpg" },
    { name: "Arsenal de Carthagène", lat: 37.600311, lng: -0.988611, audio: "audio/Arsenal_de_Carthagene.mp3", image: "images/points interets/arsenal-de-carthagene.jpg", fallbackImage: "images/points interets/Arsenal_de_Carthagene.svg", remoteImage: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Arsenal_de_Cartagena.JPG" }
];
const availableCircuits=["petit","moyen","grand"];
const circuits={"petit":[1,2,3,4,5,6,7,8,9,1],"petit_gare":[1,2,3,4,5,6,7,8,9,1],"moyen":[1,2,3,4,5,6,7,8,9,10,11,12,1],"moyen_gare":[1,2,3,4,5,6,7,8,9,10,11,12,1],"grand":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,1],"grand_gare":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,1]};
